"""empty message

Revision ID: 983d4423a519
Revises: 54f8192e6df5
Create Date: 2019-03-03 21:54:19.427929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983d4423a519'
down_revision = '54f8192e6df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'content')
    # ### end Alembic commands ###
